Hw04 auth
MarkoVoitovych/node-hw pull request #7
Opened 2023-02-17 09:11 UTC by MarkoVoitovych

also realized refresh token.
please check it.
Thanks

2023-02-17 20:49 UTC, Eastvarga requested changes
Є декілька зауважень

2023-02-17 20:49 UTC, Eastvarga commented on middlewares/authentication.js
> +    if (bearer !== 'Bearer') {
треба також  перевіряти токен на невизначеність

2023-02-17 20:49 UTC, Eastvarga commented on models/user.model.js
> +  { versionKey: false, timestamps: true },
Моделі валідації та моделі БД не повинні змішуватись (Валідація \ БД - різні модулі)

2023-02-17 20:49 UTC, Eastvarga commented on routes/api/auth.js
> +router.post('/refresh', ctrl.refresh);
тут потрібна аналогічна валідація як у authentication тільки по рефреш токену, а далі у рауті просто генерування нових токенів для юзера з реквесту

2023-02-18 09:59 UTC, MarkoVoitovych commented on routes/api/auth.js
> +router.post('/refresh', ctrl.refresh);
виконав рефакторинг

2023-02-18 09:59 UTC, MarkoVoitovych commented on models/user.model.js
> +  { versionKey: false, timestamps: true },
виконав рефакторинг

2023-02-18 09:59 UTC, MarkoVoitovych commented on middlewares/authentication.js
> +    if (bearer !== 'Bearer') {
Переписав 11 рядок на
if (bearer !== 'Bearer' || !token) {
Надіюсь ви це мали на увазі

2023-02-19 08:46 UTC, merged